# Generated by Django 4.1 on 2022-08-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.IntegerField(choices=[(1, 'A fazer'), (2, 'Fazendo'), (3, 'Concluido')]),
        ),
    ]
